name: test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24.21.0
      - uses: cypress-io/github-action@v7.4.3
        with:
          # env: PORT=4000
          build: yarn run build
          start: yarn run start
